version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d lab4"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "18080:18080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: lab4
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: