version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "18080:18080"
    environment:
      DB_HOST: postgres  # Используем имя контейнера
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: lab4
    networks:
      - test-network

networks:
  test-network:
    external: true