services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab4
    ports:
      - 5434:5432
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d lab4"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      my_network:
        ipv4_address: 172.38.0.20

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:18080:18080
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy  
    networks:
      my_network:
        ipv4_address: 172.38.0.21
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.38.0.0/16