version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "18080:18080"
    environment:
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_NAME: "lab4"
    networks:
      - test-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  test-net:
    external: true